name: ppdartw
description: |
  POC de Dart/Flutter que recrea un Planning Poker para demostrar el poder de la programación reactiva en Flutter usando Windsurf.
  El proyecto implementa arquitectura limpia y principios SOLID, empleando el patrón BLoC y dependencias provenientes del paquete jocaagura_domain.
  Flujo de datos: Services <-> Gateway (JSON) <-> Repository (Model) <-> Usecases <-> Bloc <-> UI <-> AppManager (Inyector de dependencias de nuestros BLoC) <-> Views/Pages <-> Widgets.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  jocaagura_domain: ^1.19.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
